// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: households.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addHouseholdMember = `-- name: AddHouseholdMember :one
INSERT INTO household_members (household_id, user_id)
VALUES ($1, $2)
RETURNING id, household_id, user_id, created_at, updated_at
`

type AddHouseholdMemberParams struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) AddHouseholdMember(ctx context.Context, arg AddHouseholdMemberParams) (HouseholdMember, error) {
	row := q.db.QueryRow(ctx, addHouseholdMember, arg.HouseholdID, arg.UserID)
	var i HouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateHousehold(ctx context.Context, name string) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold, name)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isHouseholdMember = `-- name: IsHouseholdMember :one
SELECT EXISTS (
    SELECT 1 FROM household_members
    WHERE household_id = $1
      AND user_id = $2
)
`

type IsHouseholdMemberParams struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) IsHouseholdMember(ctx context.Context, arg IsHouseholdMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isHouseholdMember, arg.HouseholdID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUserHouseholds = `-- name: ListUserHouseholds :many
SELECT h.id, h.name, h.created_at, h.updated_at FROM households h
JOIN household_members m ON m.household_id = h.id
WHERE m.user_id = $1
ORDER BY m.created_at
`

func (q *Queries) ListUserHouseholds(ctx context.Context, userID uuid.UUID) ([]Household, error) {
	rows, err := q.db.Query(ctx, listUserHouseholds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
