// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeInvite = `-- name: ConsumeInvite :one
DELETE FROM household_invites
WHERE code = $1
  AND expires_at > now()
RETURNING id, household_id, code, created_by, expires_at, created_at, updated_at
`

// Checks and uses the invite in one statement. If two sign-ups send the same
// code at once, only one gets the row back; the other gets no rows.
func (q *Queries) ConsumeInvite(ctx context.Context, code string) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, consumeInvite, code)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO household_invites (household_id, code, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, household_id, code, created_by, expires_at, created_at, updated_at
`

type CreateInviteParams struct {
	HouseholdID uuid.UUID
	Code        string
	CreatedBy   uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.HouseholdID,
		arg.Code,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredInvites = `-- name: DeleteExpiredInvites :execrows
DELETE FROM household_invites
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredInvites(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredInvites)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
